from typing import Protocol, Optional, List
from uuid import UUID
from app.models import (
    Configuration,
    ConfigurationCreate,
    ConfigurationUpdate,
)


class IConfigurationRepositorySync(Protocol):
    """Interfaz para el repositorio síncrono de configuraciones."""

    def create(self, data: ConfigurationCreate) -> Configuration: ...
    def get(self, configuration_id: UUID) -> Optional[Configuration]: ...
    def get_all(self, skip: int = 0, limit: int = 100) -> List[Configuration]: ...
    def update(
        self, db_configuration: Configuration, data: ConfigurationUpdate
    ) -> Configuration: ...
    def delete(self, db_configuration: Configuration) -> None: ...
    def exists(self, configuration_id: UUID) -> bool: ...
    def count(self) -> int: ...
