from typing import Protocol, List, Optional
from uuid import UUID
from app.models import Domain, DomainCreate, DomainUpdate, DomainPublicWithFeatureModels


class IDomainRepositorySync(Protocol):
    """Interfaz para el repositorio síncrono de dominios."""

    def create(self, data: DomainCreate) -> Domain: ...
    def get(self, domain_id: UUID) -> Optional[Domain]: ...
    def get_by_name(self, name: str) -> Optional[Domain]: ...
    def get_all(self, skip: int = 0, limit: int = 100) -> List[Domain]: ...
    def update(self, db_domain: Domain, data: DomainUpdate) -> Domain: ...
    def delete(self, db_domain: Domain) -> Domain: ...
    def get_with_feature_models(
        self, domain_id: UUID
    ) -> Optional[DomainPublicWithFeatureModels]: ...
    def exists(self, domain_id: UUID) -> bool: ...
    def count(self) -> int: ...
    def search(
        self, search_term: str, skip: int = 0, limit: int = 100
    ) -> List[Domain]: ...
    def count_search(self, search_term: str) -> int: ...
    def activate(self, db_domain: Domain) -> Domain: ...
    def deactivate(self, db_domain: Domain) -> Domain: ...
