from typing import Protocol, List, Optional
from uuid import UUID
from app.models import FeatureModel, FeatureModelCreate, FeatureModelUpdate


class IFeatureModelRepositorySync(Protocol):
    """Interfaz para el repositorio síncrono de feature models."""

    def create(self, data: FeatureModelCreate, owner_id: UUID) -> FeatureModel: ...
    def get(self, feature_model_id: UUID) -> Optional[FeatureModel]: ...
    def get_by_name(self, name: str, domain_id: UUID) -> Optional[FeatureModel]: ...
    def get_all(self, skip: int = 0, limit: int = 100) -> List[FeatureModel]: ...
    def get_by_domain(
        self, domain_id: UUID, skip: int = 0, limit: int = 100
    ) -> List[FeatureModel]: ...
    def update(
        self, db_feature_model: FeatureModel, data: FeatureModelUpdate
    ) -> FeatureModel: ...
    def delete(self, db_feature_model: FeatureModel) -> FeatureModel: ...
    def exists(self, feature_model_id: UUID) -> bool: ...
    def count(self, domain_id: Optional[UUID] = None) -> int: ...
