from typing import Protocol, List, Optional
from uuid import UUID
from app.models import User, UserCreate, UserUpdate


class IUserRepositorySync(Protocol):

    def create(self, data: UserCreate) -> User: ...
    def get(self, user_id: UUID) -> Optional[User]: ...
    def get_by_email(self, email: str) -> Optional[User]: ...
    def get_all(self, skip: int = 0, limit: int = 100) -> List[User]: ...
    def update(self, db_user: User, data: UserUpdate) -> User: ...
    def delete(self, db_user: User) -> User: ...
    def authenticate(self, email: str, password: str) -> Optional[User]: ...
    def change_password(
        self, db_user: User, current_password: str, new_password: str
    ) -> User: ...
    def exists(self, user_id: UUID) -> bool: ...
    def count(self) -> int: ...
    def search(
        self, search_term: str, skip: int = 0, limit: int = 100
    ) -> List[User]: ...
    def count_search(self, search_term: str) -> int: ...
    def deactivate(self, db_user: User) -> User: ...
    def activate(self, db_user: User) -> User: ...
