from typing import Protocol, Optional, List
from uuid import UUID
from app.models import (
    Configuration,
    ConfigurationCreate,
    ConfigurationUpdate,
)


class IConfigurationRepositoryAsync(Protocol):
    """Interfaz para el repositorio asíncrono de configuraciones."""

    async def create(self, data: ConfigurationCreate) -> Configuration: ...
    async def get(self, configuration_id: UUID) -> Optional[Configuration]: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> List[Configuration]: ...
    async def update(
        self, db_configuration: Configuration, data: ConfigurationUpdate
    ) -> Configuration: ...
    async def delete(self, db_configuration: Configuration) -> None: ...
    async def exists(self, configuration_id: UUID) -> bool: ...
    async def count(self) -> int: ...
