from typing import Protocol, List, Optional
from uuid import UUID
from app.models import Domain, DomainCreate, DomainUpdate, DomainPublicWithFeatureModels


class IDomainRepositoryAsync(Protocol):
    """Interfaz para el repositorio asíncrono de dominios."""

    async def create(self, data: DomainCreate) -> Domain: ...
    async def get(self, domain_id: UUID) -> Optional[Domain]: ...
    async def get_by_name(self, name: str) -> Optional[Domain]: ...
    async def get_all(
        self, skip: int = 0, limit: int = 100, include_inactive: bool = False
    ) -> List[Domain]: ...
    async def update(self, db_domain: Domain, data: DomainUpdate) -> Domain: ...
    async def delete(self, db_domain: Domain) -> Domain: ...
    async def get_with_feature_models(
        self, domain_id: UUID
    ) -> Optional[DomainPublicWithFeatureModels]: ...
    async def exists(self, domain_id: UUID) -> bool: ...
    async def count(self, include_inactive: bool = False) -> int: ...
    async def search(
        self,
        search_term: str,
        skip: int = 0,
        limit: int = 100,
        include_inactive: bool = False,
    ) -> List[Domain]: ...
    async def count_search(
        self, search_term: str, include_inactive: bool = False
    ) -> int: ...
    async def activate(self, db_domain: Domain) -> Domain: ...
    async def deactivate(self, db_domain: Domain) -> Domain: ...
