from typing import Protocol, List, Optional
from uuid import UUID
from app.models import FeatureModel, FeatureModelCreate, FeatureModelUpdate


class IFeatureModelRepositoryAsync(Protocol):
    """Interfaz para el repositorio asíncrono de feature models."""

    async def create(
        self, data: FeatureModelCreate, owner_id: UUID
    ) -> FeatureModel: ...
    async def get(self, feature_model_id: UUID) -> Optional[FeatureModel]: ...
    async def get_by_name(
        self, name: str, domain_id: UUID
    ) -> Optional[FeatureModel]: ...
    async def get_all(self, skip: int = 0, limit: int = 100) -> List[FeatureModel]: ...
    async def get_by_domain(
        self, domain_id: UUID, skip: int = 0, limit: int = 100
    ) -> List[FeatureModel]: ...
    async def update(
        self, db_feature_model: FeatureModel, data: FeatureModelUpdate
    ) -> FeatureModel: ...
    async def delete(self, db_feature_model: FeatureModel) -> FeatureModel: ...
    async def exists(self, feature_model_id: UUID) -> bool: ...
    async def count(self, domain_id: Optional[UUID] = None) -> int: ...
