from typing import Protocol, List, Optional
from uuid import UUID
from app.models import User, UserCreate, UserUpdate


class IUserRepositoryAsync(Protocol):

    async def create(self, data: UserCreate) -> User: ...
    async def get(self, user_id: UUID) -> Optional[User]: ...
    async def get_by_email(self, email: str) -> Optional[User]: ...
    async def list(self, skip: int = 0, limit: int = 100) -> List[User]: ...
    async def update(self, db_user: User, data: UserUpdate) -> User: ...
    async def delete(self, db_user: User) -> User: ...
    async def authenticate(self, email: str, password: str) -> Optional[User]: ...
    async def change_password(
        self, db_user: User, current_password: str, new_password: str
    ) -> User: ...
    async def exists(self, user_id: UUID) -> bool: ...
    async def count(self) -> int: ...
    async def search(
        self, search_term: str, skip: int = 0, limit: int = 100
    ) -> List[User]: ...
    async def count_search(self, search_term: str) -> int: ...
    async def deactivate(self, db_user: User) -> User: ...
    async def activate(self, db_user: User) -> User: ...
